# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "virt", primary: true do |virt|
    k3sserver.vm.box = "generic/centos8"
    k3sserver.vm.hostname = "virt"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = {
    }
    ansible.groups = {
      "virt" => ['virt'],
    }
    ansible.playbook = "playbook.yml"
  end
end
